// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChangesForStockEntry_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangesForStockEntry_User));
        
        string IMigrationMetadata.Id
        {
            get { return "202307311213520_ChangesForStockEntry_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
